version: "3"
services:
  server:
    build: .
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 8484:8484
      - 8585-8989:8585-8989
    volumes:
      - ./data:/kinoko/data
      - ./wz:/kinoko/wz
    environment:
      DATABASE_HOST: "database"
  database:
    image: cassandra:5.0.0-jammy
    ports:
      - 9042:9042
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 10s
      timeout: 5s
      retries: 5
